### ISSUE TITLE
tooltip shows same results for each section from the same row

### ISSUE THREAD

**Issue by DDXPP** [Quantumzhao/CourseSelection#1]
Tooltip is supposed to display the open seats and waitlist info for each section individually (on the table at right). However, it seems like the the number of open seats and waitlist stays the same for each sections on the same row, and there is no way it could be the case, since none of them are even from the same course (i.e., they are sections from different courses).

**Comment by Quantumzhao** [comment]
>  the number of open seats and waitlist stays the same for each section on the same row

I've just posted a new revision that should have this bug fixed. You can check for the latest update, and see if it is working on your machine. 

Please notify me at once if this bug still occurs.
