### ISSUE TITLE
Course Adding Issue

### ISSUE THREAD

**Issue by ja132** [Quantumzhao/CourseSelection#2]
Whenever I try to add the course ENES232 it gives me the error of "An item with the same key has already been added. Key: Discussion" This occurs even when this is the only class on the list.

**Comment by Quantumzhao** [comment]
Thanks for the issue! I will fix it by this weekend. 

But since this app cannot self-update, you might want to uninstall, and then reinstall the latest version.

**Comment by Quantumzhao** [comment]
I just published a new release. If there are still any problems, please let me know.
